### ISSUE TITLE
加载评论页面报错

### ISSUE THREAD

**Issue by m5j** [7insummer/orange-can#3]
![image](https://user-images.githubusercontent.com/13043066/34666112-a86fe4f0-f49d-11e7-9ec2-2ea9ede217f7.png)

实在是找不到哪里不对！

**Comment by m5j** [comment]
已经解决 不好意思

**Comment by quruis2002** [comment]
不好意思，刚刚看到，最近没怎么看邮件






在 2018-01-08 18:00:04，"Wujun Min" <notifications@github.com> 写道：


实在是找不到哪里不对！
